# Generated by Django 3.2.24 on 2024-02-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessLine', models.CharField(db_column='项目所属业务线', max_length=64)),
                ('description', models.CharField(db_column='项目描述', max_length=255)),
                ('ower', models.IntegerField(db_column='归属')),
                ('progress', models.IntegerField(db_column='进度')),
                ('status', models.IntegerField(db_column='项目状态： 1 进行中， 正常结束， 延期')),
                ('type', models.IntegerField(db_column='1，数科驻场，2，数科本部，3易大宗')),
                ('projectId', models.IntegerField(db_index=True, unique=True)),
                ('startup', models.DateTimeField(db_column='项目启动时间')),
                ('deadline', models.DateTimeField(db_column='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='rojectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logInfo', models.CharField(db_column='跟进信息', max_length=255)),
                ('projectId', models.IntegerField(db_column='关联项目Id')),
                ('logId', models.IntegerField(db_index=True, unique=True)),
                ('logDate', models.DateTimeField(db_column='记录时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_column='前端开发，后端开发，测试，产品经理，项目经理', max_length=128)),
                ('type', models.IntegerField(db_column='1，数科驻场，2，数科本部，3易大宗')),
                ('userid', models.IntegerField(db_index=True, unique=True)),
            ],
        ),
    ]
